apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  labels:
    app: helloworld
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 9090
      name: http
  selector:
    app: helloworld

