apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app:  helloworld
  name: helloworld-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - image: arulkumar1967/pythondockerminikube:latest
        imagePullPolicy: IfNotPresent
        name: kubecont-helloworld
        command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
        ports:
        - containerPort: 5000 
